### ISSUE TITLE
Numpy depencency for PiPy package

### ISSUE THREAD

**Issue by AndreasAntener** [dronecrew/px4tools#12]
@jgoppert hey I was just trying to build the PX4 Docker base container locally and had some issues installing px4tools:

```
Collecting pip
  Downloading pip-9.0.1-py2.py3-none-any.whl (1.3MB)
Installing collected packages: pip
  Found existing installation: pip 8.1.1
    Not uninstalling pip at /usr/lib/python2.7/dist-packages, outside environment /usr
Successfully installed pip-9.0.1
Collecting setuptools
  Downloading setuptools-32.3.0-py2.py3-none-any.whl (479kB)
Installing collected packages: setuptools
Successfully installed setuptools-32.3.0
Collecting px4tools
  Downloading px4tools-0.6.5.tar.gz
Collecting scipy (from px4tools)
  Downloading scipy-0.18.1-cp27-cp27mu-manylinux1_x86_64.whl (40.3MB)
Collecting numpy (from px4tools)
  Downloading numpy-1.11.3-cp27-cp27mu-manylinux1_x86_64.whl (15.4MB)
Collecting pandas>=0.19.1 (from px4tools)
  Downloading pandas-0.19.2-cp27-cp27mu-manylinux1_x86_64.whl (17.2MB)
Collecting transforms3d (from px4tools)
  Downloading transforms3d-0.3.zip (76kB)
Collecting pyulog (from px4tools)
  Downloading pyulog-0.0.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-zRTJvc/pyulog/setup.py", line 168, in <module>
        setup_package()
      File "/tmp/pip-build-zRTJvc/pyulog/setup.py", line 127, in setup_package
        write_version_py()
      File "/tmp/pip-build-zRTJvc/pyulog/setup.py", line 108, in write_version_py
        FULLVERSION, GIT_REVISION = get_version_info()
      File "/tmp/pip-build-zRTJvc/pyulog/setup.py", line 84, in get_version_info
        raise ImportError(str(e) + " - Unable to import git_revision. Try removing "
    ImportError: No module named numpy - Unable to import git_revision. Try removing pyulog/version.py and the build directory before building.
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-zRTJvc/pyulog/
```

It seems even though it installs numpy as part of the dependencies it cannot be used in the same "step" as installing it. I needed to install numpy beforehand, maybe you know a way around this :)

**Comment by jgoppert** [comment]
@AndreasAntener sorry I missed this. Looks like you figured it out.
